import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';
import Header from '@/components/header';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='container'>
          <div className='h-screen grid place-items-center py-4'>
            <div className='w-[min(100%,1364px)] h-[914px] rounded-[74px] border border-clr-midnight-slate relative isolate overflow-clip bg-clr-very-dark-blue/30 backdrop-blur-2xl'>
              <Image src='/pattern.png' fill alt='' className='-z-[1]' sizes='70vw' priority />
              <Header />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
